"""Initial migration

Revision ID: 922d2472f2b9
Revises: 962784f94c81
Create Date: 2024-09-11 12:35:59.579680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922d2472f2b9'
down_revision = '962784f94c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url_file', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_column('image_url_file')

    # ### end Alembic commands ###
